apiVersion: batch/v1
kind: CronJob
metadata:
  name: youtube-music-scrobbler
spec:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        kubernetes.io/arch: {{ .Values.nodeSelector.arch | quote }}
      {{- end }}
      parallelism: 1
      completions: 1
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: data-volume
              persistentVolumeClaim:
                claimName: youtube-music-scrobbler-data
            - name: browser-auth-sa
              secret:
                secretName: browser-auth-sa

          containers:
          - name: youtube-music-scrobbler
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            env:
              - name: LAST_FM_API
                valueFrom:
                  secretKeyRef:
                    key: LAST_FM_API
                    name: {{ .Values.secretName }}
              - name: LAST_FM_API_SECRET
                valueFrom:
                  secretKeyRef:
                    key: LAST_FM_API_SECRET
                    name: {{ .Values.secretName }}
              - name: LASTFM_SESSION
                valueFrom:
                  secretKeyRef:
                    key: LASTFM_SESSION
                    name: {{ .Values.secretName }}
            volumeMounts:
                - name: data-volume
                  mountPath: /data
                - name: browser-auth-sa
                  mountPath: /auth
                  readOnly: true

          imagePullSecrets:
            - name: {{ .Values.registrySecretName }}
